apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-execution-runner
  namespace: runner-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-execution-runner
  namespace: runner-prod
